baseurl: ''
profilepic: '/images/erhezi.jpg'
bkimage: '/images/clover.gif'
# google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

title: ~Hello, Erhezi~
# description: Learning sometimes may take a while


typing_text: Former epigenetic biologist, now to be determined.

# show the social network tabs
author:
  name: Erhezi
  github_username: erhezi
  linkedin_username: danli-dl
  instagram_username: a7ure
  email: dli36@syr.edu


#plugins: ['jekyll-paginate']
exclude: ['README.md']
