baseurl: ''
profilepic: '/images/erhezi.jpg'
bkimage: '/images/bk1.jpg'
# google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

title: Hello, Erhezi ~
description: Learning sometimes may take a while


typing_text: I am typing ... how about you?

# show the social network tabs
author:
  name: Erhezi
  github_username: erhezi
  linkedin_username: danli-dl
  instagram_username: a7ure
  email: dli36@syr.edu

# aboutme module
show_aboutme_card: true
about_me_title: About Me
about_me_description: Former Epigenetic biologist, now to ge determined.

# timeline module
show_timeline_card: true
timeline_title: Time Capsule


#plugins: ['jekyll-paginate']
exclude: ['README.md']
